baseurl      = "https://fffzlfk.netlify.com/"
title        = "fffzlfk's Blog"
languageCode = "en-us"
theme        = ["hugo-theme-fuji", "hugo-notice"]
paginate     = 10

enableEmoji = true
summaryLength = 10 # Custom summary length, add <!--more--> in post file to custom split point

[outputFormats]
  [outputFormats.SearchIndex]
    isPlainText = true
    notAlternative = true
    mediaType = "application/json"
    path = "/search/"

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]

[permalinks]
  post = "/:section/:filename/" # Custom post links, e.g. "/:year/:month/:title/"

[params]
  showToc = true # 对所有文章开关目录显示
  showWordCounter = true
  showReadTime = true
  prismLineNumbers = true
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  
  math        = true
  # Subtitle for home
  homeSubtitle = "Thinking will not overcome fear but action will."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]
  lazyPlaceholder = "/assets/lazyload/dsrca_loading_480x270.svg"
  # 32:9
  lazyPlaceholderRow = "/assets/lazyload/dsrca_loading_960x270.svg"
  # 8:9
  lazyPlaceholderCol = "/assets/lazyload/dsrca_loading_480x540.svg"

  # Default theme "light" or "dark"
  justifyContent = false  # Set "text-align: justify" to .post-content.

  # Default theme "light" or "dark"
  #
  defaultTheme = "light"
  themeColor = "#252627"

  # Custom footer 
  # If you want, you can easily override the default footer with your own content. 
  #
  # footerLeft = "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
  # footerRight = "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = true
    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorAnimate  = "2s"
  
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/fffzlfk"

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/fffzlfk"

  [[params.social]]
    name = "email"
    url  = "1319933925qq@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/fffzlfk"

  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/channel/UCXSyagqJBsy3s7P3gEknPsA"
  
  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/fffzlfk"
    
[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "fffzlfk's Blog"
    subtitle = "Thinking will not overcome fear but action will."
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd fffzlfk/home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable user to embed HTML snippets in Markdown content
  [markup.highlight]
    codeFences = false  # Disable Hugo's code highlighter

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3

[menu]
  [[menu.nav]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Archives"
    url = "/archives/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "Search"
    url = "/search/"
    weight = 4
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 5

  [[menu.link]]
    name = "GitHub"
    url = "https://github.com/fffzlfk"
    weight = 1
  [[menu.link]]
    name = "Twitter"
    url = "https://twitter.com/fffzlfk"
    weight = 2
  [[menu.link]]
    name = "bilibili"
    url = "https://space.bilibili.com/82433974"
    weight = 3